# application.properties
# Neon Database Connection via Environment Variables
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false

# CORS Configuration
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

# JWT Configuration
spring.jwt.issuer=${SPRING_JWT_ISSUER}
spring.jwk.set-uri=${SPRING_JWK_SET_URI}
